### ISSUE TITLE
下載不能

### ISSUE THREAD

**Issue by HKGore** [littlebtc/nicofox#36] opened 2015-03-03 09:41 UTC
一直維持在Loading不能下載.
其實已經發生了一段時間,可是貌似都沒人回報這問題,..?

nicofox: 1.0b5
firefox: 36.0 (mozilla 12:  1.0)
win 7
硬體之類的應該不寫也沒關係了吧,看以前的issue估計又是firefox更新造成...?

**Comment by magicalz** [comment] 2015-03-08 05:34
same issue
nicofox: 1.0b5
firefox:36.0.1
win8.1 64

**Comment by littlebtc** [comment] 2015-03-15 20:34
Should be the duplicate of #37.

**Closed by littlebtc** 2015-03-15 20:34 UTC

**Comment by littlebtc** [comment] 2015-03-15 22:41
我做了一個臨時的緊急修正版本，歡迎大家測試看看有沒有其他問題，沒有的話我會儘快送到 addons.mozilla.org 上

I made a quick hotfix prerelease, please test it and report any issues you encountered. If none, I will send the release to the AMO soon.

https://github.com/littlebtc/nicofox/releases/tag/1.0b6pre-hotfix

**Comment by jrdp18** [comment] 2015-03-15 23:27
It's working again now.

By the way, I saw something "Download should be able to pause =w=". Does that work? I don't think I've seen my download pause when I get disconnected to the network.

**Comment by HKGore** [comment] 2015-03-15 23:51
downloading perfectly!
